version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      - API_REDIS_HOST=redis
    ports:
      - '8080:8000'
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '6379:6379'