"""fixedname

Revision ID: ea7f746c0a34
Revises: fcd9caf0740e
Create Date: 2024-08-15 20:58:43.735796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7f746c0a34'
down_revision: Union[str, None] = 'fcd9caf0740e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('product', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('product', 'quantity')
    # ### end Alembic commands ###
